TO_PRINT = {
'OS' : [
    'AmogOS',
    'Windows 9 Professional',
    'Nyarch Linux',
    'Hannah Montana Linux',
    'Justin Bieber Linux',
    'TempleOS',
    'UwUntu',
    'Red Star OS',
    'Suicide Linux',
    'PonyOS',
    'Debian GNU/Hurd',
    'Collapse OS',
    'Plan 9',
    'Inferno',
    'Haiku',
    'Damn Small Linux',
    'GoboLinux',
    'Fatdog64',
    'Kiss Linux',
    'Source Mage GNU/Linux',
    'Venom Linux',
    'Arch Linux (btw)',
    'Exherbo',
    'OpenIndiana',
    'Illumos',
    'KolibriOS',
    ],
'Host' : [
    'Samsung Family Hub Smart Refrigerator',
    'Sony PlayStation 2',
    'Sony PlayStation 3',
    'Sony PlayStation 4',
    'OLPC XO-1',
    'Commodore C64x',
    'Atari VCS 800',
    'AmigaOne X5000',
    'Tadpole Viper',
    'DragonBox Pyra',
    'InFocus Kangaroo Mobile Desktop Pro',
    'Intel Compute Stick',
    'GPD Win Max',
    'Panasonic Toughbook CF-U1 Rugged',
    'Sega Dreamcast',
    'HP TouchPad',
    'Nintendo Wii',
    'Sony Vaio UX',
    'Chumby One',
    'Diebold Nixdorf Opteva ATM',
    'Sharp Zaurus SL-5500',
    'Neo FreeRunner',
    'Ben NanoNote',
    'Pepper Pad 3',
    'Archos 9 PC Tablet',
    'Microsoft Xbox',
    'Microsoft Xbox 360',
    'Cosmo Communicator',
    'Palm Foleo',
    'ClockworkPi DevTerm',
    'Teledyne LeCroy WaveRunner 9404 oscilloscope',
    'Xiaomi Pad 5',
    'POCO F3',
    'Linksys WRT54G Router',
    'Tesla Model 3 Infotainment Unit',
    ],
'Shell' : [
    'Fish',
    'KornShell 93',
    'Elvish',
    'Oil Shell',
    'BusyBox ash',
    'COMMAND.COM',
    'Almquist shell',
    'Loksh',
    'Heirloom Bourne Shell',
    'Scsh',
    'Ion',
    'Dash',
    'Tcsh',
    ],
'WM' : [
    'Ratpoison',
    'Blackbox',
    'Enlightenment',
    'AfterStep',
    'EvilWM',
    'Cagebreak',
    'goomwwm',
    'Sawfish',
    'Muffin',
    'Musca',
    'Notion',
    'Hikari',
    'Velox',
    'Matchbox',
    'IceWM',
],
'CPU' :[
    'Intel Itanium 2 9150M (2) @ 1.67 GHz',
    'Intel Atom N270 (1+HT) @ 1.60 GHz',
    'IBM POWER5+ (2) @ 2.20 GHz',
    'Loongson 3A2000 (4) @ 1.00 GHz',
    'VIA C3 Nehemiah (1) @ 1.20 GHz',
    'VIA Eden X2 U4200 (2) @ 1.00 GHz',
    'AMD Geode LX800 (1) @ 500 MHz',
    'Sun UltraSPARC IV (2) @ 1.50 GHz',
    'Cyrix 6x86MX PR233 (1) @ 233 MHz',
    'Transmeta Efficeon TM8800 (1) @ 1.60 GHz',
    'Transmeta Crusoe TM5800 (1) @ 1.00 GHz',
    'DEC Alpha 21264 EV67 (1) @ 667 MHz',
    'MIPS R12000 (1) @ 300 MHz',
    
],
'GPU' : [
    '3Dfx Voodoo5 9000',
    '3Dfx Voodoo Banshee',
    'NVIDIA RIVA TNT2 M64',
    'ATI Rage Fury MAXX',
    'ATI Radeon Xpress 200',
    'Matrox G400 MAX',
    'Matrox Parhelia-512',
    'S3 Savage4 Pro',
    'PowerVR KYRO II',
    'SiS Mirage 3',
    'Trident Blade 3D 9880',
    'Intel GMA X4500',
    ],
'Memory' : [
    '9 Gib / 11 GiB',
    '6 Gib / 7 GiB',
    '420 MiB / 69 Gib',
    '9001 Mib / 9000 MiB',
    '5318008 KiB / 80085 MiB',
    '7 GiB / 13 GiB',
    '666 MiB / 777 MiB',
    '3 GiB / 14 GiB',
    ],
'Locale' : [
    'zh_HK.BIG5HK@radical',
    'zh_HK.BIG5HK@stroke',
    'zh_CN.GB18030@pinyin',
    'zh_TW.EUC@zhuyin',
    'sv_SE.ISO8859-15@euro',
    'ru_RU.KOI8-R',
    'ko_KR.EUC@dict',
    'ja_JP.eucJP',
    'ku_TR.UTF-8@sorani',
    'aa_ER@saaho',
    'ca_ES@valencia',
    'gez_ER@abegede',
    'gn_PY@Latin',
    'hak_TW',
    'hr_HR',
    'ia_FR',
    'kk_KZ',
    'ayc_PE',
    'bi_TV',
    'el_CY',
    'fo_FO',
    'ff_SN',
    'hif_FJ',
    'hus_MX',
    'kab_DZ',
    'kok_IN',
    'km_KH',
    'lij_IT',
    'lo_LA',
    'mh_MH',
    'miq_NI',
    'mn_MN',
    'mnw_MM',
    'myv_RU@cyrillic',
    'nah_MX',
    'niu_NU',
    'pap_CW',
    'quy_PE',
    'sgs_LT',
    'son_ML',
    'syr',
    'the_NP',
    'tpi_PG',
    'wae_CH',
    'wal_ET',
    'yue_HK',
    'yuw_PG',
]
}
def get_user_host_name():
    from getpass import getuser
    from  socket import gethostname
    username = getuser()
    hostname = gethostname()
    return f'{username}@{hostname}'
if __name__ == '__main__':
    from random import choice
    username_AT_networking_host_name = get_user_host_name()
    print(username_AT_networking_host_name)
    print('-'*len(username_AT_networking_host_name))
    for key in TO_PRINT.keys():
        print(f'{key}: {choice(TO_PRINT[key])}')