TO_PRINT = {
'OS' : [
    'AmogOS',
    'Windows 9 Professional',
    'Nyarch Linux',
    'Hannah Montana Linux',
    'Justin Bieber Linux',
    'TempleOS',
    'UwUntu',
    'Red Star OS',
    'Suicide Linux',
    'PonyOS',
    'Debian GNU/Hurd',
    'Collapse OS',
    'Plan 9',
    'Inferno',
    'Haiku',
    'Damn Small Linux',
    'GoboLinux',
    'Fatdog64',
    'Kiss Linux',
    'Source Mage GNU/Linux',
    'Venom Linux',
    'Arch Linux (btw)',
    'Exherbo',
    'OpenIndiana',
    'Illumos',
    'KolibriOS',
    ],
'Host' : [
    'Grandma\'s Computer',
    'Potato',
    ],
'Shell' : [
    'Fish',
    'KornShell 93',
    'Elvish',
    'Oil Shell',
    'BusyBox ash',
    'COMMAND.COM',
    'Almquist shell',
    'Loksh',
    'Heirloom Bourne Shell',
    'Scsh',
    'Ion',
    'Dash',
    'Tcsh',
    ],
'WM' : [
    'Ratpoison',
    'Blackbox',
    'Enlightenment',
    'AfterStep',
    'EvilWM',
    'Cagebreak',
    'goomwwm',
    'Sawfish',
    'Muffin',
    'Musca',
    'Notion',
    'Hikari',
    'Velox',
    'Matchbox',
    'IceWM',
],
'CPU' :[
    'Intel Itanium 2 9150M (2) @ 1.67 GHz',
    'IBM POWER5+ (2) @ 2.20 GHz',
    'Loongson 3A2000 (4) @ 1.00 GHz',
    'VIA C3 Nehemiah (1) @ 1.20 GHz',
    'AMD Geode LX800 (1) @ 500 MHz',
    'Sun UltraSPARC IV (2) @ 1.50 GHz',
    'Cyrix 6x86MX PR233 (1) @ 233 MHz',
    'Transmeta Efficeon TM8800 (1) @ 1.60 GHz',
    'DEC Alpha 21264 EV67 (1) @ 667 MHz',
    'MIPS R12000 (1) @ 300 MHz',
    
],
'GPU' : [
    '3Dfx Voodoo5 9000',
    '3Dfx Voodoo Banshee',
    'NVIDIA RIVA TNT2 M64',
    'ATI Rage Fury MAXX',
    'Matrox Parhelia-512',
    'S3 Savage4 Pro',
    'PowerVR KYRO II',
    'SiS Mirage 3',
    'Trident Blade 3D 9880',
    ],
'Memory' : [
    '9 Gib / 11 GiB',
    '6 Gib / 7 GiB',
    '6 Gib / 9 GiB',
    '4 Gib / 20 GiB',
    '9001 Mib / 9000 MiB',
    ],
# 'Locale' : []
}
if __name__ == '__main__':
    from random import choice
    # username_AT_networking_host_name = ...
    # print(username_AT_networking_host_name)
    # print('-'*len(username_AT_networking_host_name))
    for key in TO_PRINT.keys():
        print(f'{key}: {choice(TO_PRINT[key])}')